name: deploy.yml
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  # Don't push anywhere yet
          tags: my-app:dry-run

      - name: Deploy (stub)
        run: "This is a fake deploy until the infrastructure is ready to support real deployment"
