name: deploy.yml
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.2

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Disable Next.JS telemetry
        uses: borales/actions-yarn@v4
        with:
          cmd: next telemetry disable

      - name: Check formatting
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

      - name: Check linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Test application
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_DOMAIN }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY_DOMAIN }}/b2b-frontend:latest
