name: deploy.yml
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.2

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Check formatting
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

      - name: Check linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Test application
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  # Don't push anywhere yet
          tags: my-app:dry-run

      - name: Deploy (stub)
        run: "echo 'This is a fake deploy until the infrastructure is ready to support real deployment'"
