name: integrate.yml
on:
  pull_request:
jobs:
  integration_test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout (Set up environment)
        uses: actions/checkout@v4

      - name: Setup Node (Set up environment)
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.2

      - name: Install dependencies (Set up environment)
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Disable Next.JS telemetry (Set up environment)
        uses: borales/actions-yarn@v4
        with:
          cmd: next telemetry disable

      - name: Check if the formatting of code follows Prettier formatting rules
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

